test: added tests for uploading documents and images.
kevinanielsen/go-fast-cdn pull request #130
Opened 2024-06-01 16:57 UTC by inlag

Added tests for the /api/cdn/upload/image/ and /api/cdn/upload/doc/ endpoints. (issue #69)

2024-06-06 12:14 UTC, kevinanielsen requested changes
You've left a few comments - otherwise everything looks great 😄

2024-06-06 12:14 UTC, kevinanielsen commented on src/handlers/docs/handleDocUpload_test.go
> +		//h := make(textproto.MIMEHeader)
What are these comments?

2024-06-13 18:05 UTC, inlag commented on src/handlers/docs/handleDocUpload_test.go
> +		//h := make(textproto.MIMEHeader)
Sorry didn't notice, corrected.

2024-06-17 19:41 UTC, kevinanielsen approved these changes

2024-06-17 19:42 UTC, kevinanielsen commented
Looks great! Thanks for the contribution!

2024-06-17 19:43 UTC, merged