feat(ui): Add a resize button to the image content card
kevinanielsen/go-fast-cdn pull request #142
Opened 2024-08-30 05:47 UTC by luckramos

Add a resize button that opens a modal and let the user change both the width and height of the image

2024-09-01 12:21 UTC, Caixetadev requested changes

2024-09-01 12:21 UTC, Caixetadev commented on ui/src/actions/handleResizeImage.ts
> +}
toast.loading returns an id, you can take this id and pass it to success and error so you don't need to use toast.dismiss
```suggestion
  const toastId = toast.loading("Renaming file...");
  axios.put(`/api/cdn/resize/image`, JSON.stringify(data)).then((res) => {
    if (res.status === 200) {
      toast.success("File resized!", { id: toastId, duration: 4000 });
      
      setTimeout(() => {
        location.reload();
      }, 1500)
    }
  }).catch((err) => {
    toast.error("Error: " + err.response.data, { id: toastId, duration: 4000 });
  })
}
```

2024-09-01 23:28 UTC, luckramos commented
fixed in commit [04c9f3d](https://github.com/kevinanielsen/go-fast-cdn/pull/142/commits/04c9f3ddc3255e7117808f08cb351c90ad1a5409)

2024-09-02 01:05 UTC, Caixetadev commented
@kevinanielsen LGTM, what do you think? Can we merge?

2024-09-09 15:00 UTC, kevinanielsen commented
> @kevinanielsen LGTM, what do you think? Can we merge?

Yeah, looks good - Nice job on this :)

2024-09-09 15:00 UTC, merged